name: uixterm

description: A Dart library for ANSI terminal colors, styles, backgrounds, and text formatting.

version: 1.0.0

repository: https://github.com/ziterz/uixterm

homepage: https://github.com/ziterz/uixterm

issue_tracker: https://github.com/ziterz/uixterm/issues

environment:
  sdk: ^3.9.0

topics:
  - terminal
  - ansi
  - console
  - cli
  - formatting
  

dependencies: {}

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.0
  dartdoc: ^8.3.3
